#version: {build}

image: Visual Studio 2017

platform:
  - x64
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - cmake -G "Visual Studio 15 2017" -A %PLATFORM% -DCMAKE_CONFIGURATION_TYPES="Debug;Release" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - build\%CONFIGURATION%\SheenBidiTester.exe Tools\Unicode
