/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_CHAR_TYPE_LOOKUP_H
#define _SB_INTERNAL_CHAR_TYPE_LOOKUP_H

#include <SBConfig.h>

#include "SBBase.h"
#include "SBCharType.h"

SB_INTERNAL SBCharType SBCharTypeDetermine(SBCodepoint codepoint);

#endif
