/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#include <SBConfig.h>
#include <SBTypes.h>

#include "SBBracketType.h"
#include "SBPairingLookup.h"

static const SBInt16 _SBPairDifferences[] = {
    0,     1,     -1,    2,     -2,    16,    -16,   3,     -3,    2016,  138,   1824,  2104,  2108,
    2106,  -138,  8,     7,     -8,    -7,    -1824, -2016, -2104, -2106, -2108
};

static const SBUInt8 _SBPairData[] = {
#define _SBPairData_000 0x000
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   3,   0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   67,  0,   132, 0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   67,  0,   132, 0,   0,
#define _SBPairData_080 0x080
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   6,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_100 0x100
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_180 0x180
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   65,  130, 65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_200 0x200
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_280 0x280
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    1,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 0,
#define _SBPairData_300 0x300
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_380 0x380
    0,   0,   0,   0,   0,   0,   0,   0,   7,   7,   7,   8,   8,   8,   0,   0,   0,   0,   0,
    0,   0,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   1,   2,   0,   0,   0,   0,   0,   10,  0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   1,   2,   1,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   1,   2,   1,   2,   1,   2,   1,   2,   0,   0,   1,   2,   1,   2,
    1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,
#define _SBPairData_400 0x400
    1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   0,   0,   0,   1,   2,   1,   2,
    0,   0,   0,   0,   0,   11,  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   2,   0,   0,
    12,  0,   13,  14,  0,   14,  0,   0,   0,   0,   1,   2,   1,   2,   1,   2,   1,   2,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   2,   1,
    2,   15,  0,   0,   1,   2,   0,   0,   0,   0,   1,   2,   1,   2,   1,   2,   1,   2,   1,
    2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   0,   0,   1,   2,
    16,  16,  16,  0,   17,  17,  0,   0,   18,  18,  18,  19,  19,  0,
#define _SBPairData_480 0x480
    0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 65,  130, 0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_500 0x500
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 65,  130, 65,  130, 65,  130, 65,  130,
    65,  130, 65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_580 0x580
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   2,   65,  130, 0,   1,   2,   0,   3,
    0,   4,   0,   0,   0,   0,   0,   0,   0,   1,   2,   0,   0,   0,   0,   0,   0,   1,   2,
    0,   0,   0,   1,   2,   1,   2,   65,  130, 65,  130, 65,  130, 65,  130, 65,  130, 0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_600 0x600
    0,   0,   0,   65,  130, 65,  130, 65,  130, 65,  130, 65,  130, 71,  129, 66,  136, 65,  130,
    65,  130, 65,  130, 65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   20,
    0,   0,   0,   0,   0,   0,   0,   1,   2,   0,   0,   1,   2,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   1,   2,   1,   2,   0,   1,   2,   0,   0,   65,  130, 65,  130, 0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   21,  0,   0,   1,   2,   0,   0,   65,  130, 0,   0,
#define _SBPairData_680 0x680
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   1,   2,   1,   2,   0,   0,   0,   0,   0,   1,   2,   0,   0,   0,
    0,   0,   0,   1,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   1,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   1,   2,   0,   0,   1,   2,   1,
#define _SBPairData_700 0x700
    2,   1,   2,   1,   2,   0,   0,   0,   0,   0,   0,   1,   2,   0,   0,   0,   0,   1,   2,
    1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   0,   0,   0,   0,   1,   2,   0,   0,   0,
    1,   2,   1,   2,   1,   2,   1,   2,   0,   1,   2,   0,   0,   1,   2,   0,   0,   0,   0,
    0,   0,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   0,   0,   0,   0,   0,
    0,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   0,   0,   0,   0,   0,   0,   0,   22,
    0,   0,   0,   0,   23,  24,  23,  0,   0,   0,   0,   0,   0,   1,   2,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   1,   2,   1,   2,   0,   0,   0,   0,   0,
#define _SBPairData_780 0x780
    0,   0,   1,   2,   1,   2,   0,   0,   0,   1,   2,   0,   1,   2,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   2,   0,   0,   1,   2,   65,  130, 65,  130,
    65,  130, 65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_800 0x800
    0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 65,  130, 65,  130, 65,  130, 65,  130, 0,
    0,   65,  130, 65,  130, 65,  130, 65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_880 0x880
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 65,  130, 65,  130,
    0,   0,   0,   0,   0,   1,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
#define _SBPairData_900 0x900
    0,   0,   0,   0,   0,   0,   0,   0,   65,  130, 0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   3,   0,   4,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   67,  0,   132, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   67,  0,   132, 0,
    65,  130, 0,   65,  130,
};

static const SBUInt16 _SBPairIndexes[] = {
    _SBPairData_000,                /**< %0000..007F*/
    _SBPairData_080,                /**< %0080..00FF*/
    _SBPairData_100,                /**< %0100..017F*/
    _SBPairData_100,                /**< %0180..01FF*/
    _SBPairData_100,                /**< %0200..027F*/
    _SBPairData_100,                /**< %0280..02FF*/
    _SBPairData_100,                /**< %0300..037F*/
    _SBPairData_100,                /**< %0380..03FF*/
    _SBPairData_100,                /**< %0400..047F*/
    _SBPairData_100,                /**< %0480..04FF*/
    _SBPairData_100,                /**< %0500..057F*/
    _SBPairData_100,                /**< %0580..05FF*/
    _SBPairData_100,                /**< %0600..067F*/
    _SBPairData_100,                /**< %0680..06FF*/
    _SBPairData_100,                /**< %0700..077F*/
    _SBPairData_100,                /**< %0780..07FF*/
    _SBPairData_100,                /**< %0800..087F*/
    _SBPairData_100,                /**< %0880..08FF*/
    _SBPairData_100,                /**< %0900..097F*/
    _SBPairData_100,                /**< %0980..09FF*/
    _SBPairData_100,                /**< %0A00..0A7F*/
    _SBPairData_100,                /**< %0A80..0AFF*/
    _SBPairData_100,                /**< %0B00..0B7F*/
    _SBPairData_100,                /**< %0B80..0BFF*/
    _SBPairData_100,                /**< %0C00..0C7F*/
    _SBPairData_100,                /**< %0C80..0CFF*/
    _SBPairData_100,                /**< %0D00..0D7F*/
    _SBPairData_100,                /**< %0D80..0DFF*/
    _SBPairData_100,                /**< %0E00..0E7F*/
    _SBPairData_100,                /**< %0E80..0EFF*/
    _SBPairData_180,                /**< %0F00..0F7F*/
    _SBPairData_100,                /**< %0F80..0FFF*/
    _SBPairData_100,                /**< %1000..107F*/
    _SBPairData_100,                /**< %1080..10FF*/
    _SBPairData_100,                /**< %1100..117F*/
    _SBPairData_100,                /**< %1180..11FF*/
    _SBPairData_100,                /**< %1200..127F*/
    _SBPairData_100,                /**< %1280..12FF*/
    _SBPairData_100,                /**< %1300..137F*/
    _SBPairData_100,                /**< %1380..13FF*/
    _SBPairData_100,                /**< %1400..147F*/
    _SBPairData_100,                /**< %1480..14FF*/
    _SBPairData_100,                /**< %1500..157F*/
    _SBPairData_100,                /**< %1580..15FF*/
    _SBPairData_100,                /**< %1600..167F*/
    _SBPairData_200,                /**< %1680..16FF*/
    _SBPairData_100,                /**< %1700..177F*/
    _SBPairData_100,                /**< %1780..17FF*/
    _SBPairData_100,                /**< %1800..187F*/
    _SBPairData_100,                /**< %1880..18FF*/
    _SBPairData_100,                /**< %1900..197F*/
    _SBPairData_100,                /**< %1980..19FF*/
    _SBPairData_100,                /**< %1A00..1A7F*/
    _SBPairData_100,                /**< %1A80..1AFF*/
    _SBPairData_100,                /**< %1B00..1B7F*/
    _SBPairData_100,                /**< %1B80..1BFF*/
    _SBPairData_100,                /**< %1C00..1C7F*/
    _SBPairData_100,                /**< %1C80..1CFF*/
    _SBPairData_100,                /**< %1D00..1D7F*/
    _SBPairData_100,                /**< %1D80..1DFF*/
    _SBPairData_100,                /**< %1E00..1E7F*/
    _SBPairData_100,                /**< %1E80..1EFF*/
    _SBPairData_100,                /**< %1F00..1F7F*/
    _SBPairData_100,                /**< %1F80..1FFF*/
    _SBPairData_280,                /**< %2000..207F*/
    _SBPairData_300,                /**< %2080..20FF*/
    _SBPairData_100,                /**< %2100..217F*/
    _SBPairData_100,                /**< %2180..21FF*/
    _SBPairData_380,                /**< %2200..227F*/
    _SBPairData_400,                /**< %2280..22FF*/
    _SBPairData_480,                /**< %2300..237F*/
    _SBPairData_100,                /**< %2380..23FF*/
    _SBPairData_100,                /**< %2400..247F*/
    _SBPairData_100,                /**< %2480..24FF*/
    _SBPairData_100,                /**< %2500..257F*/
    _SBPairData_100,                /**< %2580..25FF*/
    _SBPairData_100,                /**< %2600..267F*/
    _SBPairData_100,                /**< %2680..26FF*/
    _SBPairData_500,                /**< %2700..277F*/
    _SBPairData_580,                /**< %2780..27FF*/
    _SBPairData_100,                /**< %2800..287F*/
    _SBPairData_100,                /**< %2880..28FF*/
    _SBPairData_100,                /**< %2900..297F*/
    _SBPairData_600,                /**< %2980..29FF*/
    _SBPairData_680,                /**< %2A00..2A7F*/
    _SBPairData_700,                /**< %2A80..2AFF*/
    _SBPairData_100,                /**< %2B00..2B7F*/
    _SBPairData_100,                /**< %2B80..2BFF*/
    _SBPairData_100,                /**< %2C00..2C7F*/
    _SBPairData_100,                /**< %2C80..2CFF*/
    _SBPairData_100,                /**< %2D00..2D7F*/
    _SBPairData_100,                /**< %2D80..2DFF*/
    _SBPairData_780,                /**< %2E00..2E7F*/
    _SBPairData_100,                /**< %2E80..2EFF*/
    _SBPairData_100,                /**< %2F00..2F7F*/
    _SBPairData_100,                /**< %2F80..2FFF*/
    _SBPairData_800,                /**< %3000..307F*/
    _SBPairData_100,                /**< %3080..30FF*/
    _SBPairData_100,                /**< %3100..317F*/
    _SBPairData_100,                /**< %3180..31FF*/
    _SBPairData_100,                /**< %3200..327F*/
    _SBPairData_100,                /**< %3280..32FF*/
    _SBPairData_100,                /**< %3300..337F*/
    _SBPairData_100,                /**< %3380..33FF*/
    _SBPairData_100,                /**< %3400..347F*/
    _SBPairData_100,                /**< %3480..34FF*/
    _SBPairData_100,                /**< %3500..357F*/
    _SBPairData_100,                /**< %3580..35FF*/
    _SBPairData_100,                /**< %3600..367F*/
    _SBPairData_100,                /**< %3680..36FF*/
    _SBPairData_100,                /**< %3700..377F*/
    _SBPairData_100,                /**< %3780..37FF*/
    _SBPairData_100,                /**< %3800..387F*/
    _SBPairData_100,                /**< %3880..38FF*/
    _SBPairData_100,                /**< %3900..397F*/
    _SBPairData_100,                /**< %3980..39FF*/
    _SBPairData_100,                /**< %3A00..3A7F*/
    _SBPairData_100,                /**< %3A80..3AFF*/
    _SBPairData_100,                /**< %3B00..3B7F*/
    _SBPairData_100,                /**< %3B80..3BFF*/
    _SBPairData_100,                /**< %3C00..3C7F*/
    _SBPairData_100,                /**< %3C80..3CFF*/
    _SBPairData_100,                /**< %3D00..3D7F*/
    _SBPairData_100,                /**< %3D80..3DFF*/
    _SBPairData_100,                /**< %3E00..3E7F*/
    _SBPairData_100,                /**< %3E80..3EFF*/
    _SBPairData_100,                /**< %3F00..3F7F*/
    _SBPairData_100,                /**< %3F80..3FFF*/
    _SBPairData_100,                /**< %4000..407F*/
    _SBPairData_100,                /**< %4080..40FF*/
    _SBPairData_100,                /**< %4100..417F*/
    _SBPairData_100,                /**< %4180..41FF*/
    _SBPairData_100,                /**< %4200..427F*/
    _SBPairData_100,                /**< %4280..42FF*/
    _SBPairData_100,                /**< %4300..437F*/
    _SBPairData_100,                /**< %4380..43FF*/
    _SBPairData_100,                /**< %4400..447F*/
    _SBPairData_100,                /**< %4480..44FF*/
    _SBPairData_100,                /**< %4500..457F*/
    _SBPairData_100,                /**< %4580..45FF*/
    _SBPairData_100,                /**< %4600..467F*/
    _SBPairData_100,                /**< %4680..46FF*/
    _SBPairData_100,                /**< %4700..477F*/
    _SBPairData_100,                /**< %4780..47FF*/
    _SBPairData_100,                /**< %4800..487F*/
    _SBPairData_100,                /**< %4880..48FF*/
    _SBPairData_100,                /**< %4900..497F*/
    _SBPairData_100,                /**< %4980..49FF*/
    _SBPairData_100,                /**< %4A00..4A7F*/
    _SBPairData_100,                /**< %4A80..4AFF*/
    _SBPairData_100,                /**< %4B00..4B7F*/
    _SBPairData_100,                /**< %4B80..4BFF*/
    _SBPairData_100,                /**< %4C00..4C7F*/
    _SBPairData_100,                /**< %4C80..4CFF*/
    _SBPairData_100,                /**< %4D00..4D7F*/
    _SBPairData_100,                /**< %4D80..4DFF*/
    _SBPairData_100,                /**< %4E00..4E7F*/
    _SBPairData_100,                /**< %4E80..4EFF*/
    _SBPairData_100,                /**< %4F00..4F7F*/
    _SBPairData_100,                /**< %4F80..4FFF*/
    _SBPairData_100,                /**< %5000..507F*/
    _SBPairData_100,                /**< %5080..50FF*/
    _SBPairData_100,                /**< %5100..517F*/
    _SBPairData_100,                /**< %5180..51FF*/
    _SBPairData_100,                /**< %5200..527F*/
    _SBPairData_100,                /**< %5280..52FF*/
    _SBPairData_100,                /**< %5300..537F*/
    _SBPairData_100,                /**< %5380..53FF*/
    _SBPairData_100,                /**< %5400..547F*/
    _SBPairData_100,                /**< %5480..54FF*/
    _SBPairData_100,                /**< %5500..557F*/
    _SBPairData_100,                /**< %5580..55FF*/
    _SBPairData_100,                /**< %5600..567F*/
    _SBPairData_100,                /**< %5680..56FF*/
    _SBPairData_100,                /**< %5700..577F*/
    _SBPairData_100,                /**< %5780..57FF*/
    _SBPairData_100,                /**< %5800..587F*/
    _SBPairData_100,                /**< %5880..58FF*/
    _SBPairData_100,                /**< %5900..597F*/
    _SBPairData_100,                /**< %5980..59FF*/
    _SBPairData_100,                /**< %5A00..5A7F*/
    _SBPairData_100,                /**< %5A80..5AFF*/
    _SBPairData_100,                /**< %5B00..5B7F*/
    _SBPairData_100,                /**< %5B80..5BFF*/
    _SBPairData_100,                /**< %5C00..5C7F*/
    _SBPairData_100,                /**< %5C80..5CFF*/
    _SBPairData_100,                /**< %5D00..5D7F*/
    _SBPairData_100,                /**< %5D80..5DFF*/
    _SBPairData_100,                /**< %5E00..5E7F*/
    _SBPairData_100,                /**< %5E80..5EFF*/
    _SBPairData_100,                /**< %5F00..5F7F*/
    _SBPairData_100,                /**< %5F80..5FFF*/
    _SBPairData_100,                /**< %6000..607F*/
    _SBPairData_100,                /**< %6080..60FF*/
    _SBPairData_100,                /**< %6100..617F*/
    _SBPairData_100,                /**< %6180..61FF*/
    _SBPairData_100,                /**< %6200..627F*/
    _SBPairData_100,                /**< %6280..62FF*/
    _SBPairData_100,                /**< %6300..637F*/
    _SBPairData_100,                /**< %6380..63FF*/
    _SBPairData_100,                /**< %6400..647F*/
    _SBPairData_100,                /**< %6480..64FF*/
    _SBPairData_100,                /**< %6500..657F*/
    _SBPairData_100,                /**< %6580..65FF*/
    _SBPairData_100,                /**< %6600..667F*/
    _SBPairData_100,                /**< %6680..66FF*/
    _SBPairData_100,                /**< %6700..677F*/
    _SBPairData_100,                /**< %6780..67FF*/
    _SBPairData_100,                /**< %6800..687F*/
    _SBPairData_100,                /**< %6880..68FF*/
    _SBPairData_100,                /**< %6900..697F*/
    _SBPairData_100,                /**< %6980..69FF*/
    _SBPairData_100,                /**< %6A00..6A7F*/
    _SBPairData_100,                /**< %6A80..6AFF*/
    _SBPairData_100,                /**< %6B00..6B7F*/
    _SBPairData_100,                /**< %6B80..6BFF*/
    _SBPairData_100,                /**< %6C00..6C7F*/
    _SBPairData_100,                /**< %6C80..6CFF*/
    _SBPairData_100,                /**< %6D00..6D7F*/
    _SBPairData_100,                /**< %6D80..6DFF*/
    _SBPairData_100,                /**< %6E00..6E7F*/
    _SBPairData_100,                /**< %6E80..6EFF*/
    _SBPairData_100,                /**< %6F00..6F7F*/
    _SBPairData_100,                /**< %6F80..6FFF*/
    _SBPairData_100,                /**< %7000..707F*/
    _SBPairData_100,                /**< %7080..70FF*/
    _SBPairData_100,                /**< %7100..717F*/
    _SBPairData_100,                /**< %7180..71FF*/
    _SBPairData_100,                /**< %7200..727F*/
    _SBPairData_100,                /**< %7280..72FF*/
    _SBPairData_100,                /**< %7300..737F*/
    _SBPairData_100,                /**< %7380..73FF*/
    _SBPairData_100,                /**< %7400..747F*/
    _SBPairData_100,                /**< %7480..74FF*/
    _SBPairData_100,                /**< %7500..757F*/
    _SBPairData_100,                /**< %7580..75FF*/
    _SBPairData_100,                /**< %7600..767F*/
    _SBPairData_100,                /**< %7680..76FF*/
    _SBPairData_100,                /**< %7700..777F*/
    _SBPairData_100,                /**< %7780..77FF*/
    _SBPairData_100,                /**< %7800..787F*/
    _SBPairData_100,                /**< %7880..78FF*/
    _SBPairData_100,                /**< %7900..797F*/
    _SBPairData_100,                /**< %7980..79FF*/
    _SBPairData_100,                /**< %7A00..7A7F*/
    _SBPairData_100,                /**< %7A80..7AFF*/
    _SBPairData_100,                /**< %7B00..7B7F*/
    _SBPairData_100,                /**< %7B80..7BFF*/
    _SBPairData_100,                /**< %7C00..7C7F*/
    _SBPairData_100,                /**< %7C80..7CFF*/
    _SBPairData_100,                /**< %7D00..7D7F*/
    _SBPairData_100,                /**< %7D80..7DFF*/
    _SBPairData_100,                /**< %7E00..7E7F*/
    _SBPairData_100,                /**< %7E80..7EFF*/
    _SBPairData_100,                /**< %7F00..7F7F*/
    _SBPairData_100,                /**< %7F80..7FFF*/
    _SBPairData_100,                /**< %8000..807F*/
    _SBPairData_100,                /**< %8080..80FF*/
    _SBPairData_100,                /**< %8100..817F*/
    _SBPairData_100,                /**< %8180..81FF*/
    _SBPairData_100,                /**< %8200..827F*/
    _SBPairData_100,                /**< %8280..82FF*/
    _SBPairData_100,                /**< %8300..837F*/
    _SBPairData_100,                /**< %8380..83FF*/
    _SBPairData_100,                /**< %8400..847F*/
    _SBPairData_100,                /**< %8480..84FF*/
    _SBPairData_100,                /**< %8500..857F*/
    _SBPairData_100,                /**< %8580..85FF*/
    _SBPairData_100,                /**< %8600..867F*/
    _SBPairData_100,                /**< %8680..86FF*/
    _SBPairData_100,                /**< %8700..877F*/
    _SBPairData_100,                /**< %8780..87FF*/
    _SBPairData_100,                /**< %8800..887F*/
    _SBPairData_100,                /**< %8880..88FF*/
    _SBPairData_100,                /**< %8900..897F*/
    _SBPairData_100,                /**< %8980..89FF*/
    _SBPairData_100,                /**< %8A00..8A7F*/
    _SBPairData_100,                /**< %8A80..8AFF*/
    _SBPairData_100,                /**< %8B00..8B7F*/
    _SBPairData_100,                /**< %8B80..8BFF*/
    _SBPairData_100,                /**< %8C00..8C7F*/
    _SBPairData_100,                /**< %8C80..8CFF*/
    _SBPairData_100,                /**< %8D00..8D7F*/
    _SBPairData_100,                /**< %8D80..8DFF*/
    _SBPairData_100,                /**< %8E00..8E7F*/
    _SBPairData_100,                /**< %8E80..8EFF*/
    _SBPairData_100,                /**< %8F00..8F7F*/
    _SBPairData_100,                /**< %8F80..8FFF*/
    _SBPairData_100,                /**< %9000..907F*/
    _SBPairData_100,                /**< %9080..90FF*/
    _SBPairData_100,                /**< %9100..917F*/
    _SBPairData_100,                /**< %9180..91FF*/
    _SBPairData_100,                /**< %9200..927F*/
    _SBPairData_100,                /**< %9280..92FF*/
    _SBPairData_100,                /**< %9300..937F*/
    _SBPairData_100,                /**< %9380..93FF*/
    _SBPairData_100,                /**< %9400..947F*/
    _SBPairData_100,                /**< %9480..94FF*/
    _SBPairData_100,                /**< %9500..957F*/
    _SBPairData_100,                /**< %9580..95FF*/
    _SBPairData_100,                /**< %9600..967F*/
    _SBPairData_100,                /**< %9680..96FF*/
    _SBPairData_100,                /**< %9700..977F*/
    _SBPairData_100,                /**< %9780..97FF*/
    _SBPairData_100,                /**< %9800..987F*/
    _SBPairData_100,                /**< %9880..98FF*/
    _SBPairData_100,                /**< %9900..997F*/
    _SBPairData_100,                /**< %9980..99FF*/
    _SBPairData_100,                /**< %9A00..9A7F*/
    _SBPairData_100,                /**< %9A80..9AFF*/
    _SBPairData_100,                /**< %9B00..9B7F*/
    _SBPairData_100,                /**< %9B80..9BFF*/
    _SBPairData_100,                /**< %9C00..9C7F*/
    _SBPairData_100,                /**< %9C80..9CFF*/
    _SBPairData_100,                /**< %9D00..9D7F*/
    _SBPairData_100,                /**< %9D80..9DFF*/
    _SBPairData_100,                /**< %9E00..9E7F*/
    _SBPairData_100,                /**< %9E80..9EFF*/
    _SBPairData_100,                /**< %9F00..9F7F*/
    _SBPairData_100,                /**< %9F80..9FFF*/
    _SBPairData_100,                /**< %A000..A07F*/
    _SBPairData_100,                /**< %A080..A0FF*/
    _SBPairData_100,                /**< %A100..A17F*/
    _SBPairData_100,                /**< %A180..A1FF*/
    _SBPairData_100,                /**< %A200..A27F*/
    _SBPairData_100,                /**< %A280..A2FF*/
    _SBPairData_100,                /**< %A300..A37F*/
    _SBPairData_100,                /**< %A380..A3FF*/
    _SBPairData_100,                /**< %A400..A47F*/
    _SBPairData_100,                /**< %A480..A4FF*/
    _SBPairData_100,                /**< %A500..A57F*/
    _SBPairData_100,                /**< %A580..A5FF*/
    _SBPairData_100,                /**< %A600..A67F*/
    _SBPairData_100,                /**< %A680..A6FF*/
    _SBPairData_100,                /**< %A700..A77F*/
    _SBPairData_100,                /**< %A780..A7FF*/
    _SBPairData_100,                /**< %A800..A87F*/
    _SBPairData_100,                /**< %A880..A8FF*/
    _SBPairData_100,                /**< %A900..A97F*/
    _SBPairData_100,                /**< %A980..A9FF*/
    _SBPairData_100,                /**< %AA00..AA7F*/
    _SBPairData_100,                /**< %AA80..AAFF*/
    _SBPairData_100,                /**< %AB00..AB7F*/
    _SBPairData_100,                /**< %AB80..ABFF*/
    _SBPairData_100,                /**< %AC00..AC7F*/
    _SBPairData_100,                /**< %AC80..ACFF*/
    _SBPairData_100,                /**< %AD00..AD7F*/
    _SBPairData_100,                /**< %AD80..ADFF*/
    _SBPairData_100,                /**< %AE00..AE7F*/
    _SBPairData_100,                /**< %AE80..AEFF*/
    _SBPairData_100,                /**< %AF00..AF7F*/
    _SBPairData_100,                /**< %AF80..AFFF*/
    _SBPairData_100,                /**< %B000..B07F*/
    _SBPairData_100,                /**< %B080..B0FF*/
    _SBPairData_100,                /**< %B100..B17F*/
    _SBPairData_100,                /**< %B180..B1FF*/
    _SBPairData_100,                /**< %B200..B27F*/
    _SBPairData_100,                /**< %B280..B2FF*/
    _SBPairData_100,                /**< %B300..B37F*/
    _SBPairData_100,                /**< %B380..B3FF*/
    _SBPairData_100,                /**< %B400..B47F*/
    _SBPairData_100,                /**< %B480..B4FF*/
    _SBPairData_100,                /**< %B500..B57F*/
    _SBPairData_100,                /**< %B580..B5FF*/
    _SBPairData_100,                /**< %B600..B67F*/
    _SBPairData_100,                /**< %B680..B6FF*/
    _SBPairData_100,                /**< %B700..B77F*/
    _SBPairData_100,                /**< %B780..B7FF*/
    _SBPairData_100,                /**< %B800..B87F*/
    _SBPairData_100,                /**< %B880..B8FF*/
    _SBPairData_100,                /**< %B900..B97F*/
    _SBPairData_100,                /**< %B980..B9FF*/
    _SBPairData_100,                /**< %BA00..BA7F*/
    _SBPairData_100,                /**< %BA80..BAFF*/
    _SBPairData_100,                /**< %BB00..BB7F*/
    _SBPairData_100,                /**< %BB80..BBFF*/
    _SBPairData_100,                /**< %BC00..BC7F*/
    _SBPairData_100,                /**< %BC80..BCFF*/
    _SBPairData_100,                /**< %BD00..BD7F*/
    _SBPairData_100,                /**< %BD80..BDFF*/
    _SBPairData_100,                /**< %BE00..BE7F*/
    _SBPairData_100,                /**< %BE80..BEFF*/
    _SBPairData_100,                /**< %BF00..BF7F*/
    _SBPairData_100,                /**< %BF80..BFFF*/
    _SBPairData_100,                /**< %C000..C07F*/
    _SBPairData_100,                /**< %C080..C0FF*/
    _SBPairData_100,                /**< %C100..C17F*/
    _SBPairData_100,                /**< %C180..C1FF*/
    _SBPairData_100,                /**< %C200..C27F*/
    _SBPairData_100,                /**< %C280..C2FF*/
    _SBPairData_100,                /**< %C300..C37F*/
    _SBPairData_100,                /**< %C380..C3FF*/
    _SBPairData_100,                /**< %C400..C47F*/
    _SBPairData_100,                /**< %C480..C4FF*/
    _SBPairData_100,                /**< %C500..C57F*/
    _SBPairData_100,                /**< %C580..C5FF*/
    _SBPairData_100,                /**< %C600..C67F*/
    _SBPairData_100,                /**< %C680..C6FF*/
    _SBPairData_100,                /**< %C700..C77F*/
    _SBPairData_100,                /**< %C780..C7FF*/
    _SBPairData_100,                /**< %C800..C87F*/
    _SBPairData_100,                /**< %C880..C8FF*/
    _SBPairData_100,                /**< %C900..C97F*/
    _SBPairData_100,                /**< %C980..C9FF*/
    _SBPairData_100,                /**< %CA00..CA7F*/
    _SBPairData_100,                /**< %CA80..CAFF*/
    _SBPairData_100,                /**< %CB00..CB7F*/
    _SBPairData_100,                /**< %CB80..CBFF*/
    _SBPairData_100,                /**< %CC00..CC7F*/
    _SBPairData_100,                /**< %CC80..CCFF*/
    _SBPairData_100,                /**< %CD00..CD7F*/
    _SBPairData_100,                /**< %CD80..CDFF*/
    _SBPairData_100,                /**< %CE00..CE7F*/
    _SBPairData_100,                /**< %CE80..CEFF*/
    _SBPairData_100,                /**< %CF00..CF7F*/
    _SBPairData_100,                /**< %CF80..CFFF*/
    _SBPairData_100,                /**< %D000..D07F*/
    _SBPairData_100,                /**< %D080..D0FF*/
    _SBPairData_100,                /**< %D100..D17F*/
    _SBPairData_100,                /**< %D180..D1FF*/
    _SBPairData_100,                /**< %D200..D27F*/
    _SBPairData_100,                /**< %D280..D2FF*/
    _SBPairData_100,                /**< %D300..D37F*/
    _SBPairData_100,                /**< %D380..D3FF*/
    _SBPairData_100,                /**< %D400..D47F*/
    _SBPairData_100,                /**< %D480..D4FF*/
    _SBPairData_100,                /**< %D500..D57F*/
    _SBPairData_100,                /**< %D580..D5FF*/
    _SBPairData_100,                /**< %D600..D67F*/
    _SBPairData_100,                /**< %D680..D6FF*/
    _SBPairData_100,                /**< %D700..D77F*/
    _SBPairData_100,                /**< %D780..D7FF*/
    _SBPairData_100,                /**< %D800..D87F*/
    _SBPairData_100,                /**< %D880..D8FF*/
    _SBPairData_100,                /**< %D900..D97F*/
    _SBPairData_100,                /**< %D980..D9FF*/
    _SBPairData_100,                /**< %DA00..DA7F*/
    _SBPairData_100,                /**< %DA80..DAFF*/
    _SBPairData_100,                /**< %DB00..DB7F*/
    _SBPairData_100,                /**< %DB80..DBFF*/
    _SBPairData_100,                /**< %DC00..DC7F*/
    _SBPairData_100,                /**< %DC80..DCFF*/
    _SBPairData_100,                /**< %DD00..DD7F*/
    _SBPairData_100,                /**< %DD80..DDFF*/
    _SBPairData_100,                /**< %DE00..DE7F*/
    _SBPairData_100,                /**< %DE80..DEFF*/
    _SBPairData_100,                /**< %DF00..DF7F*/
    _SBPairData_100,                /**< %DF80..DFFF*/
    _SBPairData_100,                /**< %E000..E07F*/
    _SBPairData_100,                /**< %E080..E0FF*/
    _SBPairData_100,                /**< %E100..E17F*/
    _SBPairData_100,                /**< %E180..E1FF*/
    _SBPairData_100,                /**< %E200..E27F*/
    _SBPairData_100,                /**< %E280..E2FF*/
    _SBPairData_100,                /**< %E300..E37F*/
    _SBPairData_100,                /**< %E380..E3FF*/
    _SBPairData_100,                /**< %E400..E47F*/
    _SBPairData_100,                /**< %E480..E4FF*/
    _SBPairData_100,                /**< %E500..E57F*/
    _SBPairData_100,                /**< %E580..E5FF*/
    _SBPairData_100,                /**< %E600..E67F*/
    _SBPairData_100,                /**< %E680..E6FF*/
    _SBPairData_100,                /**< %E700..E77F*/
    _SBPairData_100,                /**< %E780..E7FF*/
    _SBPairData_100,                /**< %E800..E87F*/
    _SBPairData_100,                /**< %E880..E8FF*/
    _SBPairData_100,                /**< %E900..E97F*/
    _SBPairData_100,                /**< %E980..E9FF*/
    _SBPairData_100,                /**< %EA00..EA7F*/
    _SBPairData_100,                /**< %EA80..EAFF*/
    _SBPairData_100,                /**< %EB00..EB7F*/
    _SBPairData_100,                /**< %EB80..EBFF*/
    _SBPairData_100,                /**< %EC00..EC7F*/
    _SBPairData_100,                /**< %EC80..ECFF*/
    _SBPairData_100,                /**< %ED00..ED7F*/
    _SBPairData_100,                /**< %ED80..EDFF*/
    _SBPairData_100,                /**< %EE00..EE7F*/
    _SBPairData_100,                /**< %EE80..EEFF*/
    _SBPairData_100,                /**< %EF00..EF7F*/
    _SBPairData_100,                /**< %EF80..EFFF*/
    _SBPairData_100,                /**< %F000..F07F*/
    _SBPairData_100,                /**< %F080..F0FF*/
    _SBPairData_100,                /**< %F100..F17F*/
    _SBPairData_100,                /**< %F180..F1FF*/
    _SBPairData_100,                /**< %F200..F27F*/
    _SBPairData_100,                /**< %F280..F2FF*/
    _SBPairData_100,                /**< %F300..F37F*/
    _SBPairData_100,                /**< %F380..F3FF*/
    _SBPairData_100,                /**< %F400..F47F*/
    _SBPairData_100,                /**< %F480..F4FF*/
    _SBPairData_100,                /**< %F500..F57F*/
    _SBPairData_100,                /**< %F580..F5FF*/
    _SBPairData_100,                /**< %F600..F67F*/
    _SBPairData_100,                /**< %F680..F6FF*/
    _SBPairData_100,                /**< %F700..F77F*/
    _SBPairData_100,                /**< %F780..F7FF*/
    _SBPairData_100,                /**< %F800..F87F*/
    _SBPairData_100,                /**< %F880..F8FF*/
    _SBPairData_100,                /**< %F900..F97F*/
    _SBPairData_100,                /**< %F980..F9FF*/
    _SBPairData_100,                /**< %FA00..FA7F*/
    _SBPairData_100,                /**< %FA80..FAFF*/
    _SBPairData_100,                /**< %FB00..FB7F*/
    _SBPairData_100,                /**< %FB80..FBFF*/
    _SBPairData_100,                /**< %FC00..FC7F*/
    _SBPairData_100,                /**< %FC80..FCFF*/
    _SBPairData_100,                /**< %FD00..FD7F*/
    _SBPairData_100,                /**< %FD80..FDFF*/
    _SBPairData_880,                /**< %FE00..FE7F*/
    _SBPairData_100,                /**< %FE80..FEFF*/
    _SBPairData_900             /**< %FF00..FF63*/
};

SB_INTERNAL SBCodepoint SBPairingDetermineMirror(SBCodepoint codepoint)
{
    if (codepoint <= 0xFF63) {
        SBInt16 diff = _SBPairDifferences[
                        _SBPairData[
                         _SBPairIndexes[
                              codepoint / 0x080
                         ] + (codepoint % 0x080)
                        ] & SBBracketTypeInverseMask
                       ];

        if (diff != 0) {
            return (codepoint + diff);
        }
    }

    return 0;
}

SB_INTERNAL SBCodepoint SBPairingDetermineBracketPair(SBCodepoint codepoint, SBBracketType *type)
{
    if (codepoint <= 0xFF63) {
        SBUInt8 data = _SBPairData[
                        _SBPairIndexes[
                             codepoint / 0x080
                        ] + (codepoint % 0x080)
                       ];
        *type = (data & SBBracketTypePrimaryMask);

        if (*type != 0) {
            SBInt16 diff = _SBPairDifferences[
                            data & SBBracketTypeInverseMask
                           ];
            return (codepoint + diff);
        }
    } else {
        *type = SBBracketTypeNone;
    }

    return 0;
}
