/*
 * Automatically generated by SheenBidiGenerator tool. 
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H
#define _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H

#include <SBBase.h>
#include <SBCodepoint.h>
#include <SBConfig.h>
#include <SBGeneralCategory.h>

SB_INTERNAL SBGeneralCategory LookupGeneralCategory(SBCodepoint codepoint);

#endif
