/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_BIDI_TYPE_LOOKUP_H
#define _SB_INTERNAL_BIDI_TYPE_LOOKUP_H

#include <SBConfig.h>
#include "SBBase.h"

SB_INTERNAL SBBidiType SBBidiTypeDetermine(SBCodepoint codepoint);

#endif
