/*
 * Automatically generated by SheenBidiGenerator tool. 
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H
#define _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H

#include <SBConfig.h>

#include "SBBase.h"
#include "SBGeneralCategory.h"

SB_INTERNAL SBGeneralCategory SBGeneralCategoryDetermine(SBCodepoint codepoint);

#endif
