/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_SCRIPT_LOOKUP_H
#define _SB_INTERNAL_SCRIPT_LOOKUP_H

#include <SBConfig.h>

#include "SBBase.h"
#include "SBScript.h"

SB_INTERNAL SBScript SBScriptDetermine(SBCodepoint codepoint);

#endif
