name: CMake build and test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: macos-latest
            compiler: clang
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
        run: sudo apt install lcov

      # The library targets C89, so we force C89 compatibility in CI.
      # We do not force it by default in CMake because that can cause
      # build errors if the stdlib headers require a newer C standard.
      - name: Configure CMake
        run: |
          EXTRA_FLAGS=""
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.compiler }}" == "gcc" ]]; then
            EXTRA_FLAGS="-DENABLE_CODECOVERAGE=ON"
          fi
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_STANDARD=90 -DCMAKE_C_EXTENSIONS=OFF -DCMAKE_C_STANDARD_REQUIRED=ON $EXTRA_FLAGS

      - name: Build
        run: cmake --build build -j $(getconf _NPROCESSORS_ONLN)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -j $(getconf _NPROCESSORS_ONLN)

      - name: Generate Coverage Report
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' 'Tools/*' --output-file coverage.info

      - name: Upload to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.info
